server:
  port: 8093

spring:
  application:
    name: song-service
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:localhost}:${DB_PORT:5342}/songdb
    username: root
    password: 1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  metrics:
    export:
      elastic:
        enabled: true
        host: http://elasticsearch:9200
        index: metrics
        step: 5s
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always