CREATE TABLE IF NOT EXISTS songs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  artist VARCHAR(100) NOT NULL,
  album VARCHAR(100) NOT NULL,
  length VARCHAR(100) NOT NULL,
  resource_id BIGINT NOT NULL,
  release_year VARCHAR(100) NOT NULL
);