version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
  resource:
    image: resource
    container_name: resource-service-application
    build: resource/
    ports:
      - "8091:8091"
    depends_on:
      - kafka
      - localstack
      - db-postgres
    environment:
      KAFKA_DOCKER_SERVICE: ${KAFKA_DOCKER_SERVICE}
      LOCALSTACK_SERVICE: ${LOCALSTACK_SERVICE}
      SERVICE_TO_KAFKA_CONNECTION: ${SERVICE_TO_KAFKA_CONNECTION}
      SERVICE_TO_KAFKA_PORT: ${SERVICE_TO_KAFKA_PORT}
      DB_SERVICE: ${DB_SERVICE}
      DB_PORT: ${DB_PORT}
  processor:
    image: processor
    container_name: processor-service-application
    build: processor/
    ports:
      - "8092:8092"
    depends_on:
      - kafka
      - localstack
    environment:
      KAFKA_DOCKER_SERVICE: ${KAFKA_DOCKER_SERVICE}
      RESOURCE_SERVICE_HOST: ${RESOURCE_SERVICE_HOST}
      SONG_SERVICE_HOST: ${SONG_SERVICE_HOST}
      SERVICE_TO_KAFKA_CONNECTION: ${SERVICE_TO_KAFKA_CONNECTION}
      SERVICE_TO_KAFKA_PORT: ${SERVICE_TO_KAFKA_PORT}
  song:
    image: song
    container_name: song-service-application
    build: song/
    ports:
      - "8093:8093"
    depends_on:
      - kafka
      - localstack
      - db-postgres
    environment:
      DB_SERVICE: ${DB_SERVICE}
      DB_PORT: ${DB_PORT}
  db-postgres:
    image: postgres
    container_name: db-postgres-container
    restart: always
    ports:
      - "5343:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      SERVICES: ${LOCALSTACK_SERVICES}
      DOCKER_HOST: ${LOCALSTACK_DOCKER_HOST}
