server:
  port: 8091

spring:
  application:
    name: resource-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:localhost}:${DB_PORT:5342}/resourcedb
    username: root
    password: 1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SERVICE_TO_KAFKA_CONNECTION}:${SERVICE_TO_KAFKA_PORT}

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

aws:
  s3:
    endpoint-url: http://${LOCALSTACK_SERVICE:127.0.0.1}:4566
    bucket-name: songsbucket

kafka:
  consumer:
    group-id: songsapp
  topic-upload: resource-upload

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
