server:
  port: 8094

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:localhost}:${DB_PORT:5342}/storagedb
    username: root
    password: 1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI}/realms/music-service-realm
          jwt-set-uri: ${KEYCLOAK_URI}/realms/music-service-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  metrics:
    export:
      elastic:
        enabled: true
        host: http://elasticsearch:9200
        index: metrics
        step: 5s
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always